# Generated by Django 2.2.3 on 2019-07-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InicioSesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('ruc', models.CharField(max_length=13)),
                ('register_date', models.DateTimeField(verbose_name='Registro cliente')),
            ],
        ),
    ]
