# Generated by Django 2.2.3 on 2019-07-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InicioSesion',
        ),
    ]
